name: File size and name checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: configure git
        run: |
          git config --global user.email "1583854+ElliottLandsborough@users.noreply.github.com"
          git config --global user.name "ElliottLandsborough"

      # Switch to whatever branch we are on
      - name: get current branch
        run: |
          git config pull.rebase true
          git pull origin ${GITHUB_HEAD_REF}

      - name: Bring resolution down to 1080x1080, 80% qual on jpg/jpeg files over 500K big
        run: find . -type f -regex ".*\.\(jpg\|jpeg\)" -size +500k -exec convert {} -resize 1080x1080 -quality 80% {} \;

      # Twice, once to actually output the list, second time to output non zero and break CI
      - name: List jpg/jpeg files that are too large
        run: |
         find . -regex ".*\.\(jpg\|jpeg\)" -type f -size +500k
         find . -regex ".*\.\(jpg\|jpeg\)" -type f -size +500k -exec false {} +

      - name: Remove spaces from filenames
        run: find . -type f -name "* *" | while read file; do mv "$file" ${file// /_}; done

      - name: Display a list of uppercase files
        run: find . -name "*.*[A-Z]*" ! -name "*.*[^A-Z]*"

      - name: Find uppercase 'JPG' and rename to lowercase 'jpg'
        run: find . -depth -name '*.JPG' -type f -exec bash -c 'base=${0%.*} ext=${0##*.} a=${base,,}.${ext,,}; [ "$a" != "$0" ] && mv -- "$0" "$a"' {} \;

      - name: Display a list of uppercase files
        run: find . -name "*.*[A-Z]*" ! -name "*.*[^A-Z]*"

      - name: Commit report
        run: |
          if [[ $(git status -s) ]]; then
            git add -A
            git commit -m "Fix bad files"
            git push origin HEAD:${GITHUB_HEAD_REF}
          fi